### ISSUE TITLE
Old Title Bar issue

### ISSUE THREAD

**Issue by jaaneh** [SyndiShanX/Discord-Dark#8]
Hey. Thank you for the great theme!

The import of the "Old Title Bar" CSS is creating some issues for me.

The title bar has a `top: 1px` applied, which creates a space at the very top of the client. This image is taken in a Discord server with a server banner while the client is full size of a 24" monitor.
![](https://jaany.xyz/i/rfdkk.png)

Another issue also appears when trying to click icons that are aligned right of the title bar. Here is a picture of me watching a screen share and hovering that area. In this example, the chat icon appears below the window title bar and becomes unclickable.
![](https://jaany.xyz/i/rj2i3.png)

Both of these issues are fixed if the Old Title Bar import is commented out since it no longer absolute positions the title bar, or adds a `top: 1px` style.

**Comment by SyndiShanX** [comment]
I pushed a Fix for various issues with the Title Bar, but I can't replicate the issue with screen sharing, I don't have that chat button on my screen

![image](https://user-images.githubusercontent.com/23367120/221268174-d4656f4d-d230-468b-b1ea-4dcf7abadfe9.png)

**Comment by jaaneh** [comment]
The fix pushed did not resolve the issue on my end, and my user profile is now pushed below the screen.
![](https://jaany.xyz/i/2vcsk.png)

This is my view when in a call and hovering title bar. I do not have any other themes enabled, and only have ZeroPluginLibrary plugin installed and enabled. 
![image](https://user-images.githubusercontent.com/27323317/221294721-f42803bc-0abb-4a82-a6a9-b03d5392e88c.png)

I can try do some more debugging, but from what I can tell it's caused by the `Old Title Bar` import.

**Comment by ShardusBlunder** [comment]
I have a similar issue.
![image](https://user-images.githubusercontent.com/110431568/221298192-8d0026a9-2586-47d4-87b1-475e28c8c39a.png)
This also causes issues when trying to update plugins since the pop up for the notifications will be covered by other UI sometimes.

**Comment by SyndiShanX** [comment]
Hopefully I fixed the bottom overflowing, but idk how to fix the other issues as I don't have them on my end

**Comment by jaaneh** [comment]
Bottom overflow seems fine for me now, yeah. Still have the same issue as @ShardusBlunder shows.
@SyndiShanX do you have any custom CSS or other plugin/themes enabled maybe?

**Comment by PhantomXY** [comment]
![image](https://user-images.githubusercontent.com/74013223/221347879-c437ccd2-34cd-41af-a45e-b2dc8895d2f0.png)

It seems that i am facing a similar issue that to my knowledge occurred after a recent discord update. I do not use "Old Title Bar" and after removing "Main Theme File" it fixed the problem, my guess is that there are some conflicts regarding that

**Comment by SyndiShanX** [comment]
I disabled all plugins and other themes and couldn't find the issue, maybe I'm not looking in the right spots, what areas are you in that cause these issues?

**Comment by SyndiShanX** [comment]
This is what I see while in a screen sharing call hovering over the title bar for example
![Screenshot (235)](https://user-images.githubusercontent.com/23367120/221378749-a541ae4e-e915-49bd-9a54-3037a637383f.png)

**Comment by SyndiShanX** [comment]
Ok, so it seems like for some reason the version I use to edit the theme locally and the release version have differences in how they're displayed for some reason despite being virtually identical, I fixed the title bar being cutoff, but I still can't find the chat icon issue

**Comment by PhantomXY** [comment]
the chat icon issue seems to only occur when you streaming or watching a stream other than that the fix you pushed seems to fix everything else, but in my case i use your theme without the "Old Title Bar" which made my situation worse. In the time being I'll use it until you manage to find and fix the bug that is causing it so no stress :)

**Comment by SyndiShanX** [comment]
Should be fixed, thanks for reporting
